//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetTaskAdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarDrawing
    {
        public decimal Drw_Id { get; set; }
        public string Drw_Name { get; set; }
        public Nullable<decimal> Drw_JobId { get; set; }
        public Nullable<System.DateTime> Drw_StDate { get; set; }
        public Nullable<System.DateTime> Drw_EndDate { get; set; }
        public Nullable<System.DateTime> Drw_DeliveryDate { get; set; }
        public Nullable<decimal> Drw_employeeid { get; set; }
        public Nullable<double> Drw_Est { get; set; }
        public Nullable<double> Drw_RevEst { get; set; }
        public Nullable<bool> Drw_Archive { get; set; }
        public string Drw_NameOld { get; set; }
        public Nullable<byte> Drw_Gate1 { get; set; }
        public Nullable<byte> Drw_Gate2 { get; set; }
        public Nullable<byte> Drw_Gate3 { get; set; }
        public Nullable<byte> Drw_Gate4 { get; set; }
        public Nullable<int> Drw_CreatedBy { get; set; }
        public Nullable<System.DateTime> Drw_CreatedDate { get; set; }
        public Nullable<int> Drw_UpdatedBy { get; set; }
        public Nullable<System.DateTime> Drw_UpdatedDate { get; set; }
        public Nullable<byte> Drw_Status { get; set; }
    }
}
