//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimesheetTaskAdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarJob
    {
        public decimal Job_Id { get; set; }
        public string Job_No { get; set; }
        public string Job_Name { get; set; }
        public Nullable<decimal> Job_ProjectId { get; set; }
        public Nullable<System.DateTime> Job_StDate { get; set; }
        public Nullable<System.DateTime> Job_EndDate { get; set; }
        public Nullable<double> Job_Est { get; set; }
        public Nullable<bool> Job_Archive { get; set; }
        public Nullable<int> Job_CreatedBy { get; set; }
        public Nullable<System.DateTime> Job_CreatedDate { get; set; }
        public Nullable<int> Job_UpdatedBy { get; set; }
        public Nullable<System.DateTime> Job_UpdatedDate { get; set; }
    }
}
